
spring:
  data:
    mongodb:
      host: 37.233.98.86
      port: 27017
      database: rpg_db
      username: rpgUser
      password: Ha$lo123

auth:
  url: "http://localhost:5000/auth"
  key: "ranfsa532fsa"